export enum RoutingPathFragments {
  ROOT = '/',
  MAP = 'map',
  SETTINGS = 'settings',
  CONTACT = 'contact',
  SPOTS = 'spots',
  EXAMPLES = 'examples',
  CHANGE_DETECTOR = 'change-detector',
  STYLES = 'styles',
  RXJS_OPERATORS = 'rxjs-operators',
  HIGHER_ORDER_MAPPING = 'higher-order-mapping',
  FORK_JOIN = 'fork-join',
  COMBINE_LATEST = 'combine-latest',
  NG_ZONE = 'ng-zone',
  WORKER = 'worker',
  LIFECYCLE_HOOKS = 'lifecycle-hooks',
  CUSTOM_TEMPLATE_LIST = 'custom-template-list',
  REGISTER = 'register',
  NOT_FOUND = '404',
}
